# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='shopper_app.Item'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopper_app.ShoppingList'),
        ),
    ]
